services:
  auth_service:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: auth_service_dev

    ports:
      - "${APP_PORT}:8000"

    volumes:
      - ../src/:/app/src

    env_file:
      - ../.env

    networks:
      - default
      - kafka_network

    depends_on:
      postgres_auth:
        condition: service_healthy
      postgres_test_auth:
        condition: service_healthy

    command: "uvicorn --factory src.presentation.api.main:create_app --timeout-graceful-shutdown 2 --reload --log-level info --host 0.0.0.0 --port 8000"


networks:
  default:
    driver: bridge
  kafka_network:
    external: True
    name: kafka_network