services:
  auth_service:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: auth_service_dev

    hostname: auth_service

    ports:
      - "${APP_PORT}:8000"

    volumes:
      - ../src/:/app/src

    tty: true

    env_file:
      - ../.env

    networks:
      - default
      - kafka_network
      - redis_network
      - auth_service.grafana.network

    depends_on:
      postgres_auth:
        condition: service_healthy
      postgres_test_auth:
        condition: service_healthy

    command: "uvicorn --factory src.presentation.api.main:create_app --timeout-graceful-shutdown 2  --use-colors --reload  --log-level debug --host 0.0.0.0 --port 8000"
    labels:
      - "alloy.logs.enable=true"

networks:
  default:
    driver: bridge

  kafka_network:
    external: True
    name: kafka_network

  redis_network:
    external: True
    name: redis_network

  auth_service.grafana.network:
      external: True
      name: auth_service.grafana.network
