services:
  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    restart: always
    volumes:
      - postgres_auth_service_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_auth_service_data: