from src.application.base.exception import ApplicationException
from src.application.exceptions.jwt import (
    AccessRejectedException,
    AuthenticationException,
    AuthorizationException,
    MappingProviderException,
    TokenExpiredException,
    TokenRevokedException,
    TokenValidationError,
)
from src.application.exceptions.mediator import (
    CommandIsNotRegisteredException,
    EventIsNotRegisteredException,
    QueryIsNotRegisteredException,
)
from src.application.exceptions.oauth import (
    OAuthAccountAlreadyDeactivatedException,
    OAuthAccountDoesNotExistException,
)
from src.application.exceptions.rbac import (
    AccessDeniedException,
    PermissionAlreadyExistsException,
    PermissionInUseException,
    PermissionNotFoundException,
    RBACException,
    RoleAlreadyExistsException,
    RoleCreationAccessDeniedException,
    RoleInUseException,
    RoleNotFoundException,
    UnauthorizedRBACOperationException,
    ValidationException,
)
from src.application.exceptions.user import (
    EmailAlreadyExistsException,
    EmailTokenExpiredException,
    OAuthConnectionTokenExpiredException,
    PasswordIsInvalidException,
    PasswordTokenExpiredException,
    UsernameAlreadyExistsException,
    UserNotFoundException,
)

__all__ = (
    "AccessDeniedException",
    "AccessRejectedException",
    "ApplicationException",
    "AuthenticationException",
    "AuthorizationException",
    "CommandIsNotRegisteredException",
    "EmailAlreadyExistsException",
    "EmailTokenExpiredException",
    "EventIsNotRegisteredException",
    "MappingProviderException",
    "OAuthAccountAlreadyDeactivatedException",
    "OAuthAccountDoesNotExistException",
    "OAuthConnectionTokenExpiredException",
    "PasswordIsInvalidException",
    "PasswordTokenExpiredException",
    "PermissionAlreadyExistsException",
    "PermissionInUseException",
    "PermissionNotFoundException",
    "QueryIsNotRegisteredException",
    "RBACException",
    "RoleAlreadyExistsException",
    "RoleCreationAccessDeniedException",
    "RoleInUseException",
    "RoleNotFoundException",
    "TokenExpiredException",
    "TokenRevokedException",
    "TokenValidationError",
    "UnauthorizedRBACOperationException",
    "UserNotFoundException",
    "UsernameAlreadyExistsException",
    "ValidationException",
)
