from typing import Protocol


class ResponseProtocol(Protocol):
    def set_cookie(self, key: str, value: str, **kwargs: dict) -> None: ...
    def delete_cookie(self, key: str, **kwargs: dict) -> None: ...
