global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files (uncomment if you add alerting rules later)
# rule_files:
#   - "rules/*.yml"

scrape_configs:
  # Self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape metrics from Alloy/Grafana Agent
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]

  # Scrape your auth service directly (if it exposes Prometheus metrics)
  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service_dev:8000"]
    metrics_path: /metrics
