global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files (uncomment if you add alerting rules later)
# rule_files:
#   - "rules/*.yml"

scrape_configs:
  # Self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape metrics from Alloy/Grafana Agent
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]

  # Scrape your auth service directly (if it exposes Prometheus metrics)
  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service_dev:8000", "172.27.0.2:8000"]
    metrics_path: /metrics

  # Docker auto-discovery (to find containers automatically)
  - job_name: "docker"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      # Only keep containers that have a specific label
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep
      # Use the container name as the instance label
      - source_labels: [__meta_docker_container_name]
        target_label: instance
        regex: "/(.*)"
        replacement: "$1"
      # Get metrics path from label if specified
      - source_labels: [__meta_docker_container_label_prometheus_metrics_path]
        regex: "(.+)"
        target_label: __metrics_path__
        replacement: "$1"